### ISSUE TITLE
Great job! Can you share the latest version of train.py?

### ISSUE THREAD

**Issue by Wonderdch** [GGorMM1/QIREN#1]
In the inr-gan/README.md we can see:
> You can run the code with the following command
python train.py --outdir=./training-runs --data=./data/FFHQ32x32.zip --gpus=4

But there is no outdir parameter in train.py. 😅

I know it takes courage to work on open source, but it really helps the quantum community.

**Comment by Wonderdch** [comment]
By the way, the work is really good 👍

**Comment by GGorMM1** [comment]
Thank you for recognizing our work. There was a mistake in uploading where we mistakenly uploaded 'tarin.py' from 'qinr' to 'inr-gan'. We have now corrected this error.

**Comment by Wonderdch** [comment]
感谢，之前有幸听过 张鹏 老师的线上分享，受益良多😁
